### PR TITLE
Correct the registry link in the readme

### PR DESCRIPTION
**Pull request by amymaraisane7f**
Noticed this when cruising through our public repos, working on documentation for the wiki

### CODE REVIEW

**Comment by amymaraisane7f** [comment]
Not really sure if we would want to do a patch release for this, or just no release

**Review by dumptruckman — APPROVED** [review]
Nice catch. Thanks!

**Comment by dumptruckman** [comment]
For posterity: we are trying "no release" to see if the readme over on the registry will be updated without a release.

**Comment by dumptruckman** [comment]
Turns out that a release is required to update the readme over on the registry.

**Pull request merged**
